/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagraph;

import javax.swing.*;
import java.util.*;
import java.io.*;
import static javagraph.AddEdge.vet;
/**
 *
 * @author javed
 */
class VertexComparator implements Comparator<Graph>
{ 
   public int compare (Graph a, Graph b)
   {
       return a.getVertex().compareTo(b.getVertex());
   }
}   

class EdgeComparator implements Comparator<Edge>
{
    public int compare(Edge a, Edge b)
    {
        if(a.getV1().getVertex().equals(b.getV1().getVertex()))
            return a.getV2().getVertex().compareTo(b.getV2().getVertex());
        else
           return a.getV1().getVertex().compareTo(b.getV1().getVertex());
    }
}

public class ExportGraph extends javax.swing.JFrame {

    static ArrayList<Graph> vet;
    static ArrayList<Edge> edt;
    /**
     * Creates new form ExportGraph
     */
    public ExportGraph(ArrayList<Graph> vet ,ArrayList<Edge> edt ) {
        initComponents();
        this.vet = vet;
        this.edt =edt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vv = new javax.swing.JTextField();
        uu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("        Export Graph");

        jLabel2.setText("Enter File Name");

        uu.setText("Export");
        uu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(uu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(uu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uuActionPerformed
       
       String output = vv.getText().trim();
       
       ArrayList<Graph> arr = new ArrayList<Graph>(vet);
       ArrayList<Edge> temp = new ArrayList<Edge>(edt);
       
       Collections.sort(arr , new VertexComparator());
       Collections.sort(temp , new EdgeComparator());
       
       try
       {
           FileWriter writer = new FileWriter(output,true);
           for(int i = 0; i < arr.size(); i++)
           {
               String word = arr.get(i).getVertex() + " " + arr.get(i).getX() + " " + arr.get(i).getY();
               writer.write(word);
               writer.write(System.getProperty("line.separator"));
           }
           for(int i = 0; i < temp.size(); i++)
           {
               String worde = temp.get(i).getV1().getVertex() + " " +temp.get(i).getV2().getVertex()+ " " + temp.get(i).getWeight();
               writer.write(worde);
               writer.write(System.getProperty("line.separator"));
           }
           writer.close();
           JOptionPane.showMessageDialog(null , "Succesfully Written");
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null , e.getMessage());
       }
    }//GEN-LAST:event_uuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportGraph(vet,edt).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton uu;
    private javax.swing.JTextField vv;
    // End of variables declaration//GEN-END:variables
}
