/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagraph;

import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author javed
 */
public class UploadVertex extends javax.swing.JFrame {
    
    static ArrayList<Graph> vet;
    static ArrayList<Edge> edt; 
    /**
     * Creates new form UploadVertex
     */
    public UploadVertex(ArrayList<Graph> vet, ArrayList<Edge> edt) {
        initComponents();
        this.vet = vet;
        this.edt = edt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vv = new javax.swing.JTextField();
        uu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("       Upload Vertex");

        jLabel2.setText("    Enter File Name");

        vv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vvActionPerformed(evt);
            }
        });

        uu.setText("Upload");
        uu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(uu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(uu)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vvActionPerformed

    private void uuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uuActionPerformed
        String input = vv.getText().trim();
        //System.out.println(input);
        try
       {
          //Make connections to the file
          FileInputStream file = new FileInputStream(input);
          try
          {
              Scanner s = new Scanner(file);
          
              while(s.hasNext())
              {
                 String q = s.nextLine();
                 if(q.length() == 0)
                 break;
                 String words[] = q.split(" ");
                 int num = Integer.parseInt(words[0]);
          
                 while(num>0)
                {
                  String x = s.nextLine();
                  String worde[] = x.split(" ");
             
                  
                  String name = worde[0];
                 try
                {
                    if(worde[1].equals(null))
                    {
                        int nums = Integer.parseInt(worde[0]);
                    }
                }
                catch(NumberFormatException e)
                {
                    System.out.println("Wrong Format Input");
                }
                  String r = worde[1];
                  String y = worde[2];
             
                  Graph g = new Graph(name , Double.parseDouble(r), Double.parseDouble(y));
             
                  vet.add(g);
                  num = num-1;
                }
             
                String q1 = s.nextLine();

                if(q1.length() == 0)
                 break;
                String wordt[] = q1.split(" ");
               
                int num1 = Integer.parseInt(wordt[0]);
                while(num1 > 0)
               {
                  String x1 = s.nextLine();
                  String wordy[]= x1.split(" ");
                  
                  String src = wordy[0];
                  String dest = wordy[1];
                  String weit = wordy[2];
                  
                  Graph g1=null , g2=null;
                  
                  for(int i = 0; i < vet.size(); i++)
                  {
                      if(vet.get(i).getVertex().equals(src))
                      {
                           g1 = vet.get(i);                          
                      }
                      if(vet.get(i).getVertex().equals(dest))
                      {
                           g2 = vet.get(i);                          
                      }
                  }
                  if(g1!=null && g2!=null)
                  { 
                     Edge temp = new Edge(g1, g2 ,Double.parseDouble(weit));
                     edt.add(temp);
                  }
                  num1 = num1-1;
               }
              }
              JOptionPane.showMessageDialog(null, "Successfully Read From Input File");
            }
            catch(Exception f)
            {
              JOptionPane.showMessageDialog(null, f.getMessage());  
            }
            finally 
            {
               file.close();      
            }
       }
       catch(IOException e)
      {
        JOptionPane.showMessageDialog(null, e.getMessage());
      }  
    }//GEN-LAST:event_uuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadVertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadVertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadVertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadVertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadVertex(vet,edt).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton uu;
    private javax.swing.JTextField vv;
    // End of variables declaration//GEN-END:variables
}
